version = 1

[[packages]]
name = "darkfactory-rust"
registry = "crates"
crate = "darkfactory"
path = "packages/rust"
first_version = "0.0.1"
files = [
  "packages/rust/**",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE",
]
