/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A word and how many times it occurred. */
export interface Entry {
  word: string
  count: number
}
export declare function version(): string
/** The CLI, run in-process via the shared Rust implementation. Returns the exit code. */
export declare function runCli(args: Array<string>): number
/** Tallies word frequencies over text streamed in via `add`. */
export declare class Counter {
  constructor(caseSensitive?: boolean | undefined | null)
  add(text: string): void
  count(word: string): number
  /** Total tokens added. */
  get total(): number
  /** Number of distinct words. */
  get size(): number
  has(word: string): boolean
  /** All entries in deterministic order (count desc, then word asc). */
  entries(): Array<Entry>
  /** The `n` most common entries. Throws an `Error` with `code === "InvalidArg"` on negative `n`. */
  mostCommon(n: number): Array<Entry>
}
