# Type stubs for the compiled PyO3 module. Hand-written for now; the agreed setup is to
# generate these with pyo3-stub-gen and gate freshness in CI (regenerate-and-diff).
from typing import final

__version__: str

class WordCountError(Exception): ...

@final
class Entry:
    def __init__(self, word: str, count: int) -> None: ...
    @property
    def word(self) -> str: ...
    @property
    def count(self) -> int: ...

@final
class Counter:
    def __init__(self, *, case_sensitive: bool = ...) -> None: ...
    def add(self, text: str) -> None: ...
    def count(self, word: str) -> int: ...
    @property
    def total(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, word: str) -> bool: ...
    def entries(self) -> list[Entry]: ...
    def most_common(self, n: int) -> list[Entry]: ...

def run_cli(args: list[str]) -> int: ...
